# Generated by Django 5.0.1 on 2024-02-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theme_responses', to='app.theme'),
            preserve_default=False,
        ),
    ]
