# Generated by Django 5.0.1 on 2024-02-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_questionresponse_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='userquestionresponse',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_questions', to='app.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquestionresponse',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_themes', to='app.theme'),
        ),
    ]
